// Autogenerated from Pigeon (v1.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.ingenico.flutter_sdk;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Messages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SessionRequest {
    private String clientSessionId;
    public String getClientSessionId() { return clientSessionId; }
    public void setClientSessionId(String setterArg) { this.clientSessionId = setterArg; }

    private String customerId;
    public String getCustomerId() { return customerId; }
    public void setCustomerId(String setterArg) { this.customerId = setterArg; }

    private String clientApiUrl;
    public String getClientApiUrl() { return clientApiUrl; }
    public void setClientApiUrl(String setterArg) { this.clientApiUrl = setterArg; }

    private String assetBaseUrl;
    public String getAssetBaseUrl() { return assetBaseUrl; }
    public void setAssetBaseUrl(String setterArg) { this.assetBaseUrl = setterArg; }

    private Boolean environmentIsProduction;
    public Boolean getEnvironmentIsProduction() { return environmentIsProduction; }
    public void setEnvironmentIsProduction(Boolean setterArg) { this.environmentIsProduction = setterArg; }

    private String applicationIdentifier;
    public String getApplicationIdentifier() { return applicationIdentifier; }
    public void setApplicationIdentifier(String setterArg) { this.applicationIdentifier = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("clientSessionId", clientSessionId);
      toMapResult.put("customerId", customerId);
      toMapResult.put("clientApiUrl", clientApiUrl);
      toMapResult.put("assetBaseUrl", assetBaseUrl);
      toMapResult.put("environmentIsProduction", environmentIsProduction);
      toMapResult.put("applicationIdentifier", applicationIdentifier);
      return toMapResult;
    }
    static SessionRequest fromMap(Map<String, Object> map) {
      SessionRequest fromMapResult = new SessionRequest();
      Object clientSessionId = map.get("clientSessionId");
      fromMapResult.clientSessionId = (String)clientSessionId;
      Object customerId = map.get("customerId");
      fromMapResult.customerId = (String)customerId;
      Object clientApiUrl = map.get("clientApiUrl");
      fromMapResult.clientApiUrl = (String)clientApiUrl;
      Object assetBaseUrl = map.get("assetBaseUrl");
      fromMapResult.assetBaseUrl = (String)assetBaseUrl;
      Object environmentIsProduction = map.get("environmentIsProduction");
      fromMapResult.environmentIsProduction = (Boolean)environmentIsProduction;
      Object applicationIdentifier = map.get("applicationIdentifier");
      fromMapResult.applicationIdentifier = (String)applicationIdentifier;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SessionResponse {
    private String sessionId;
    public String getSessionId() { return sessionId; }
    public void setSessionId(String setterArg) { this.sessionId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("sessionId", sessionId);
      return toMapResult;
    }
    static SessionResponse fromMap(Map<String, Object> map) {
      SessionResponse fromMapResult = new SessionResponse();
      Object sessionId = map.get("sessionId");
      fromMapResult.sessionId = (String)sessionId;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PaymentContextRequest {
    private String sessionId;
    public String getSessionId() { return sessionId; }
    public void setSessionId(String setterArg) { this.sessionId = setterArg; }

    private Double amountValue;
    public Double getAmountValue() { return amountValue; }
    public void setAmountValue(Double setterArg) { this.amountValue = setterArg; }

    private String currencyCode;
    public String getCurrencyCode() { return currencyCode; }
    public void setCurrencyCode(String setterArg) { this.currencyCode = setterArg; }

    private String countryCode;
    public String getCountryCode() { return countryCode; }
    public void setCountryCode(String setterArg) { this.countryCode = setterArg; }

    private Boolean isRecurring;
    public Boolean getIsRecurring() { return isRecurring; }
    public void setIsRecurring(Boolean setterArg) { this.isRecurring = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("sessionId", sessionId);
      toMapResult.put("amountValue", amountValue);
      toMapResult.put("currencyCode", currencyCode);
      toMapResult.put("countryCode", countryCode);
      toMapResult.put("isRecurring", isRecurring);
      return toMapResult;
    }
    static PaymentContextRequest fromMap(Map<String, Object> map) {
      PaymentContextRequest fromMapResult = new PaymentContextRequest();
      Object sessionId = map.get("sessionId");
      fromMapResult.sessionId = (String)sessionId;
      Object amountValue = map.get("amountValue");
      fromMapResult.amountValue = (Double)amountValue;
      Object currencyCode = map.get("currencyCode");
      fromMapResult.currencyCode = (String)currencyCode;
      Object countryCode = map.get("countryCode");
      fromMapResult.countryCode = (String)countryCode;
      Object isRecurring = map.get("isRecurring");
      fromMapResult.isRecurring = (Boolean)isRecurring;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GetPaymentProductRequest {
    private String sessionId;
    public String getSessionId() { return sessionId; }
    public void setSessionId(String setterArg) { this.sessionId = setterArg; }

    private String paymentProductId;
    public String getPaymentProductId() { return paymentProductId; }
    public void setPaymentProductId(String setterArg) { this.paymentProductId = setterArg; }

    private Double amountValue;
    public Double getAmountValue() { return amountValue; }
    public void setAmountValue(Double setterArg) { this.amountValue = setterArg; }

    private String currencyCode;
    public String getCurrencyCode() { return currencyCode; }
    public void setCurrencyCode(String setterArg) { this.currencyCode = setterArg; }

    private String countryCode;
    public String getCountryCode() { return countryCode; }
    public void setCountryCode(String setterArg) { this.countryCode = setterArg; }

    private Boolean isRecurring;
    public Boolean getIsRecurring() { return isRecurring; }
    public void setIsRecurring(Boolean setterArg) { this.isRecurring = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("sessionId", sessionId);
      toMapResult.put("paymentProductId", paymentProductId);
      toMapResult.put("amountValue", amountValue);
      toMapResult.put("currencyCode", currencyCode);
      toMapResult.put("countryCode", countryCode);
      toMapResult.put("isRecurring", isRecurring);
      return toMapResult;
    }
    static GetPaymentProductRequest fromMap(Map<String, Object> map) {
      GetPaymentProductRequest fromMapResult = new GetPaymentProductRequest();
      Object sessionId = map.get("sessionId");
      fromMapResult.sessionId = (String)sessionId;
      Object paymentProductId = map.get("paymentProductId");
      fromMapResult.paymentProductId = (String)paymentProductId;
      Object amountValue = map.get("amountValue");
      fromMapResult.amountValue = (Double)amountValue;
      Object currencyCode = map.get("currencyCode");
      fromMapResult.currencyCode = (String)currencyCode;
      Object countryCode = map.get("countryCode");
      fromMapResult.countryCode = (String)countryCode;
      Object isRecurring = map.get("isRecurring");
      fromMapResult.isRecurring = (Boolean)isRecurring;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PaymentContextResponse {
    private List<BasicPaymentProduct> basicPaymentProduct;
    public List<BasicPaymentProduct> getBasicPaymentProduct() { return basicPaymentProduct; }
    public void setBasicPaymentProduct(List<BasicPaymentProduct> setterArg) { this.basicPaymentProduct = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("basicPaymentProduct", basicPaymentProduct);
      return toMapResult;
    }
    static PaymentContextResponse fromMap(Map<String, Object> map) {
      PaymentContextResponse fromMapResult = new PaymentContextResponse();
      Object basicPaymentProduct = map.get("basicPaymentProduct");
      fromMapResult.basicPaymentProduct = (List<BasicPaymentProduct>)basicPaymentProduct;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DisplayHintsPaymentItem {
    private Long displayOrder;
    public Long getDisplayOrder() { return displayOrder; }
    public void setDisplayOrder(Long setterArg) { this.displayOrder = setterArg; }

    private String label;
    public String getLabel() { return label; }
    public void setLabel(String setterArg) { this.label = setterArg; }

    private String logoUrl;
    public String getLogoUrl() { return logoUrl; }
    public void setLogoUrl(String setterArg) { this.logoUrl = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("displayOrder", displayOrder);
      toMapResult.put("label", label);
      toMapResult.put("logoUrl", logoUrl);
      return toMapResult;
    }
    static DisplayHintsPaymentItem fromMap(Map<String, Object> map) {
      DisplayHintsPaymentItem fromMapResult = new DisplayHintsPaymentItem();
      Object displayOrder = map.get("displayOrder");
      fromMapResult.displayOrder = (displayOrder == null) ? null : ((displayOrder instanceof Integer) ? (Integer)displayOrder : (Long)displayOrder);
      Object label = map.get("label");
      fromMapResult.label = (String)label;
      Object logoUrl = map.get("logoUrl");
      fromMapResult.logoUrl = (String)logoUrl;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PaymentProduct {
    private String id;
    public String getId() { return id; }
    public void setId(String setterArg) { this.id = setterArg; }

    private String paymentMethod;
    public String getPaymentMethod() { return paymentMethod; }
    public void setPaymentMethod(String setterArg) { this.paymentMethod = setterArg; }

    private String paymentProductGroup;
    public String getPaymentProductGroup() { return paymentProductGroup; }
    public void setPaymentProductGroup(String setterArg) { this.paymentProductGroup = setterArg; }

    private Double minAmount;
    public Double getMinAmount() { return minAmount; }
    public void setMinAmount(Double setterArg) { this.minAmount = setterArg; }

    private Double maxAmount;
    public Double getMaxAmount() { return maxAmount; }
    public void setMaxAmount(Double setterArg) { this.maxAmount = setterArg; }

    private Boolean allowsRecurring;
    public Boolean getAllowsRecurring() { return allowsRecurring; }
    public void setAllowsRecurring(Boolean setterArg) { this.allowsRecurring = setterArg; }

    private Boolean allowsTokenization;
    public Boolean getAllowsTokenization() { return allowsTokenization; }
    public void setAllowsTokenization(Boolean setterArg) { this.allowsTokenization = setterArg; }

    private Boolean usesRedirectionTo3rdParty;
    public Boolean getUsesRedirectionTo3rdParty() { return usesRedirectionTo3rdParty; }
    public void setUsesRedirectionTo3rdParty(Boolean setterArg) { this.usesRedirectionTo3rdParty = setterArg; }

    private DisplayHintsPaymentItem displayHints;
    public DisplayHintsPaymentItem getDisplayHints() { return displayHints; }
    public void setDisplayHints(DisplayHintsPaymentItem setterArg) { this.displayHints = setterArg; }

    private List<PaymentProductField> fields;
    public List<PaymentProductField> getFields() { return fields; }
    public void setFields(List<PaymentProductField> setterArg) { this.fields = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("id", id);
      toMapResult.put("paymentMethod", paymentMethod);
      toMapResult.put("paymentProductGroup", paymentProductGroup);
      toMapResult.put("minAmount", minAmount);
      toMapResult.put("maxAmount", maxAmount);
      toMapResult.put("allowsRecurring", allowsRecurring);
      toMapResult.put("allowsTokenization", allowsTokenization);
      toMapResult.put("usesRedirectionTo3rdParty", usesRedirectionTo3rdParty);
      toMapResult.put("displayHints", (displayHints == null) ? null : displayHints.toMap());
      toMapResult.put("fields", fields);
      return toMapResult;
    }
    static PaymentProduct fromMap(Map<String, Object> map) {
      PaymentProduct fromMapResult = new PaymentProduct();
      Object id = map.get("id");
      fromMapResult.id = (String)id;
      Object paymentMethod = map.get("paymentMethod");
      fromMapResult.paymentMethod = (String)paymentMethod;
      Object paymentProductGroup = map.get("paymentProductGroup");
      fromMapResult.paymentProductGroup = (String)paymentProductGroup;
      Object minAmount = map.get("minAmount");
      fromMapResult.minAmount = (Double)minAmount;
      Object maxAmount = map.get("maxAmount");
      fromMapResult.maxAmount = (Double)maxAmount;
      Object allowsRecurring = map.get("allowsRecurring");
      fromMapResult.allowsRecurring = (Boolean)allowsRecurring;
      Object allowsTokenization = map.get("allowsTokenization");
      fromMapResult.allowsTokenization = (Boolean)allowsTokenization;
      Object usesRedirectionTo3rdParty = map.get("usesRedirectionTo3rdParty");
      fromMapResult.usesRedirectionTo3rdParty = (Boolean)usesRedirectionTo3rdParty;
      Object displayHints = map.get("displayHints");
      fromMapResult.displayHints = DisplayHintsPaymentItem.fromMap((Map)displayHints);
      Object fields = map.get("fields");
      fromMapResult.fields = (List<PaymentProductField>)fields;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PaymentRequest {
    private Map<String, String> values;
    public Map<String, String> getValues() { return values; }
    public void setValues(Map<String, String> setterArg) { this.values = setterArg; }

    private String paymentProductId;
    public String getPaymentProductId() { return paymentProductId; }
    public void setPaymentProductId(String setterArg) { this.paymentProductId = setterArg; }

    private Boolean tokenize;
    public Boolean getTokenize() { return tokenize; }
    public void setTokenize(Boolean setterArg) { this.tokenize = setterArg; }

    private String sessionId;
    public String getSessionId() { return sessionId; }
    public void setSessionId(String setterArg) { this.sessionId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("values", values);
      toMapResult.put("paymentProductId", paymentProductId);
      toMapResult.put("tokenize", tokenize);
      toMapResult.put("sessionId", sessionId);
      return toMapResult;
    }
    static PaymentRequest fromMap(Map<String, Object> map) {
      PaymentRequest fromMapResult = new PaymentRequest();
      Object values = map.get("values");
      fromMapResult.values = (Map<String, String>)values;
      Object paymentProductId = map.get("paymentProductId");
      fromMapResult.paymentProductId = (String)paymentProductId;
      Object tokenize = map.get("tokenize");
      fromMapResult.tokenize = (Boolean)tokenize;
      Object sessionId = map.get("sessionId");
      fromMapResult.sessionId = (String)sessionId;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PreparedPaymentRequest {
    private String encryptedFields;
    public String getEncryptedFields() { return encryptedFields; }
    public void setEncryptedFields(String setterArg) { this.encryptedFields = setterArg; }

    private String encodedClientMetaInfo;
    public String getEncodedClientMetaInfo() { return encodedClientMetaInfo; }
    public void setEncodedClientMetaInfo(String setterArg) { this.encodedClientMetaInfo = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("encryptedFields", encryptedFields);
      toMapResult.put("encodedClientMetaInfo", encodedClientMetaInfo);
      return toMapResult;
    }
    static PreparedPaymentRequest fromMap(Map<String, Object> map) {
      PreparedPaymentRequest fromMapResult = new PreparedPaymentRequest();
      Object encryptedFields = map.get("encryptedFields");
      fromMapResult.encryptedFields = (String)encryptedFields;
      Object encodedClientMetaInfo = map.get("encodedClientMetaInfo");
      fromMapResult.encodedClientMetaInfo = (String)encodedClientMetaInfo;
      return fromMapResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class ApiCodec extends StandardMessageCodec {
    public static final ApiCodec INSTANCE = new ApiCodec();
    private ApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return GetPaymentProductRequest.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)129:         
          return PaymentContextRequest.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)130:         
          return PaymentContextResponse.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)131:         
          return PaymentProduct.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)132:         
          return PaymentRequest.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)133:         
          return PreparedPaymentRequest.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)134:         
          return SessionRequest.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)135:         
          return SessionResponse.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof GetPaymentProductRequest) {
        stream.write(128);
        writeValue(stream, ((GetPaymentProductRequest) value).toMap());
      } else 
      if (value instanceof PaymentContextRequest) {
        stream.write(129);
        writeValue(stream, ((PaymentContextRequest) value).toMap());
      } else 
      if (value instanceof PaymentContextResponse) {
        stream.write(130);
        writeValue(stream, ((PaymentContextResponse) value).toMap());
      } else 
      if (value instanceof PaymentProduct) {
        stream.write(131);
        writeValue(stream, ((PaymentProduct) value).toMap());
      } else 
      if (value instanceof PaymentRequest) {
        stream.write(132);
        writeValue(stream, ((PaymentRequest) value).toMap());
      } else 
      if (value instanceof PreparedPaymentRequest) {
        stream.write(133);
        writeValue(stream, ((PreparedPaymentRequest) value).toMap());
      } else 
      if (value instanceof SessionRequest) {
        stream.write(134);
        writeValue(stream, ((SessionRequest) value).toMap());
      } else 
      if (value instanceof SessionResponse) {
        stream.write(135);
        writeValue(stream, ((SessionResponse) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface Api {
    SessionResponse initClientSession(SessionRequest request);
    void getBasicPaymentItems(PaymentContextRequest request, Result<PaymentContextResponse> result);
    void getPaymentProduct(GetPaymentProductRequest request, Result<PaymentProduct> result);
    void preparePaymentRequest(PaymentRequest request, Result<PreparedPaymentRequest> result);

    /** The codec used by Api. */
    static MessageCodec<Object> getCodec() {
      return ApiCodec.INSTANCE;
    }

    /** Sets up an instance of `Api` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, Api api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.initClientSession", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              SessionRequest requestArg = (SessionRequest)args.get(0);
              if (requestArg == null) {
                throw new NullPointerException("requestArg unexpectedly null.");
              }
              SessionResponse output = api.initClientSession(requestArg);
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.getBasicPaymentItems", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              PaymentContextRequest requestArg = (PaymentContextRequest)args.get(0);
              if (requestArg == null) {
                throw new NullPointerException("requestArg unexpectedly null.");
              }
              Result<PaymentContextResponse> resultCallback = new Result<PaymentContextResponse>() {
                public void success(PaymentContextResponse result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.getBasicPaymentItems(requestArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.getPaymentProduct", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              GetPaymentProductRequest requestArg = (GetPaymentProductRequest)args.get(0);
              if (requestArg == null) {
                throw new NullPointerException("requestArg unexpectedly null.");
              }
              Result<PaymentProduct> resultCallback = new Result<PaymentProduct>() {
                public void success(PaymentProduct result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.getPaymentProduct(requestArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.preparePaymentRequest", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              PaymentRequest requestArg = (PaymentRequest)args.get(0);
              if (requestArg == null) {
                throw new NullPointerException("requestArg unexpectedly null.");
              }
              Result<PreparedPaymentRequest> resultCallback = new Result<PreparedPaymentRequest>() {
                public void success(PreparedPaymentRequest result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.preparePaymentRequest(requestArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
