// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString*, id>* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface SessionRequest ()
+(SessionRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface SessionResponse ()
+(SessionResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface PaymentContextRequest ()
+(PaymentContextRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface PaymentContextResponse ()
+(PaymentContextResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation SessionRequest
+(SessionRequest*)fromMap:(NSDictionary*)dict {
  SessionRequest* result = [[SessionRequest alloc] init];
  result.clientSessionId = dict[@"clientSessionId"];
  if ((NSNull *)result.clientSessionId == [NSNull null]) {
    result.clientSessionId = nil;
  }
  result.customerId = dict[@"customerId"];
  if ((NSNull *)result.customerId == [NSNull null]) {
    result.customerId = nil;
  }
  result.clientApiUrl = dict[@"clientApiUrl"];
  if ((NSNull *)result.clientApiUrl == [NSNull null]) {
    result.clientApiUrl = nil;
  }
  result.assetBaseUrl = dict[@"assetBaseUrl"];
  if ((NSNull *)result.assetBaseUrl == [NSNull null]) {
    result.assetBaseUrl = nil;
  }
  result.environmentIsProduction = dict[@"environmentIsProduction"];
  if ((NSNull *)result.environmentIsProduction == [NSNull null]) {
    result.environmentIsProduction = nil;
  }
  result.applicationIdentifier = dict[@"applicationIdentifier"];
  if ((NSNull *)result.applicationIdentifier == [NSNull null]) {
    result.applicationIdentifier = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.clientSessionId ? self.clientSessionId : [NSNull null]), @"clientSessionId", (self.customerId ? self.customerId : [NSNull null]), @"customerId", (self.clientApiUrl ? self.clientApiUrl : [NSNull null]), @"clientApiUrl", (self.assetBaseUrl ? self.assetBaseUrl : [NSNull null]), @"assetBaseUrl", (self.environmentIsProduction ? self.environmentIsProduction : [NSNull null]), @"environmentIsProduction", (self.applicationIdentifier ? self.applicationIdentifier : [NSNull null]), @"applicationIdentifier", nil];
}
@end

@implementation SessionResponse
+(SessionResponse*)fromMap:(NSDictionary*)dict {
  SessionResponse* result = [[SessionResponse alloc] init];
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", nil];
}
@end

@implementation PaymentContextRequest
+(PaymentContextRequest*)fromMap:(NSDictionary*)dict {
  PaymentContextRequest* result = [[PaymentContextRequest alloc] init];
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  result.amountValue = dict[@"amountValue"];
  if ((NSNull *)result.amountValue == [NSNull null]) {
    result.amountValue = nil;
  }
  result.currencyCode = dict[@"currencyCode"];
  if ((NSNull *)result.currencyCode == [NSNull null]) {
    result.currencyCode = nil;
  }
  result.countryCode = dict[@"countryCode"];
  if ((NSNull *)result.countryCode == [NSNull null]) {
    result.countryCode = nil;
  }
  result.isRecurring = dict[@"isRecurring"];
  if ((NSNull *)result.isRecurring == [NSNull null]) {
    result.isRecurring = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", (self.amountValue ? self.amountValue : [NSNull null]), @"amountValue", (self.currencyCode ? self.currencyCode : [NSNull null]), @"currencyCode", (self.countryCode ? self.countryCode : [NSNull null]), @"countryCode", (self.isRecurring ? self.isRecurring : [NSNull null]), @"isRecurring", nil];
}
@end

@implementation PaymentContextResponse
+(PaymentContextResponse*)fromMap:(NSDictionary*)dict {
  PaymentContextResponse* result = [[PaymentContextResponse alloc] init];
  result.basicPaymentProduct = dict[@"basicPaymentProduct"];
  if ((NSNull *)result.basicPaymentProduct == [NSNull null]) {
    result.basicPaymentProduct = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.basicPaymentProduct ? self.basicPaymentProduct : [NSNull null]), @"basicPaymentProduct", nil];
}
@end

@interface ApiCodecReader : FlutterStandardReader
@end
@implementation ApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 127:     
      return [PaymentContextRequest fromMap:[self readValue]];
    
    case 126:     
      return [PaymentContextResponse fromMap:[self readValue]];
    
    case 125:     
      return [SessionRequest fromMap:[self readValue]];
    
    case 124:     
      return [SessionResponse fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface ApiCodecWriter : FlutterStandardWriter
@end
@implementation ApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[PaymentContextRequest class]]) {
    [self writeByte:127];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[PaymentContextResponse class]]) {
    [self writeByte:126];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[SessionRequest class]]) {
    [self writeByte:125];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[SessionResponse class]]) {
    [self writeByte:124];
    [self writeValue:[value toMap]];
  }
  else {
    [super writeValue:value];
  }
}
@end

@interface ApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ApiCodecReaderWriter
- (FlutterStandardWriter*)writerWithData:(NSMutableData*)data {
  return [[ApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader*)readerWithData:(NSData*)data {
  return [[ApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec>* ApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec* s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    ApiCodecReaderWriter* readerWriter = [[ApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void ApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<Api> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.initClientSession"
        binaryMessenger:binaryMessenger
        codec:ApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        SessionRequest *input = [SessionRequest fromMap:message];
        FlutterError *error;
        SessionResponse *output = [api initClientSession:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.getBasicPaymentItems"
        binaryMessenger:binaryMessenger
        codec:ApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        PaymentContextRequest *input = [PaymentContextRequest fromMap:message];
        [api getBasicPaymentItems:input completion:^(PaymentContextResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult([output toMap], error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
