// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString*, id>* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface FLTSessionRequest ()
+(FLTSessionRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTSessionResponse ()
+(FLTSessionResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTPaymentContextRequest ()
+(FLTPaymentContextRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTGetPaymentProductRequest ()
+(FLTGetPaymentProductRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTPaymentContextResponse ()
+(FLTPaymentContextResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTDisplayHintsPaymentItem ()
+(FLTDisplayHintsPaymentItem*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTPaymentProduct ()
+(FLTPaymentProduct*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTPaymentRequest ()
+(FLTPaymentRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTPreparedPaymentRequest ()
+(FLTPreparedPaymentRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation FLTSessionRequest
+(FLTSessionRequest*)fromMap:(NSDictionary*)dict {
  FLTSessionRequest* result = [[FLTSessionRequest alloc] init];
  result.clientSessionId = dict[@"clientSessionId"];
  if ((NSNull *)result.clientSessionId == [NSNull null]) {
    result.clientSessionId = nil;
  }
  result.customerId = dict[@"customerId"];
  if ((NSNull *)result.customerId == [NSNull null]) {
    result.customerId = nil;
  }
  result.clientApiUrl = dict[@"clientApiUrl"];
  if ((NSNull *)result.clientApiUrl == [NSNull null]) {
    result.clientApiUrl = nil;
  }
  result.assetBaseUrl = dict[@"assetBaseUrl"];
  if ((NSNull *)result.assetBaseUrl == [NSNull null]) {
    result.assetBaseUrl = nil;
  }
  result.environmentIsProduction = dict[@"environmentIsProduction"];
  if ((NSNull *)result.environmentIsProduction == [NSNull null]) {
    result.environmentIsProduction = nil;
  }
  result.applicationIdentifier = dict[@"applicationIdentifier"];
  if ((NSNull *)result.applicationIdentifier == [NSNull null]) {
    result.applicationIdentifier = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.clientSessionId ? self.clientSessionId : [NSNull null]), @"clientSessionId", (self.customerId ? self.customerId : [NSNull null]), @"customerId", (self.clientApiUrl ? self.clientApiUrl : [NSNull null]), @"clientApiUrl", (self.assetBaseUrl ? self.assetBaseUrl : [NSNull null]), @"assetBaseUrl", (self.environmentIsProduction ? self.environmentIsProduction : [NSNull null]), @"environmentIsProduction", (self.applicationIdentifier ? self.applicationIdentifier : [NSNull null]), @"applicationIdentifier", nil];
}
@end

@implementation FLTSessionResponse
+(FLTSessionResponse*)fromMap:(NSDictionary*)dict {
  FLTSessionResponse* result = [[FLTSessionResponse alloc] init];
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", nil];
}
@end

@implementation FLTPaymentContextRequest
+(FLTPaymentContextRequest*)fromMap:(NSDictionary*)dict {
  FLTPaymentContextRequest* result = [[FLTPaymentContextRequest alloc] init];
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  result.amountValue = dict[@"amountValue"];
  if ((NSNull *)result.amountValue == [NSNull null]) {
    result.amountValue = nil;
  }
  result.currencyCode = dict[@"currencyCode"];
  if ((NSNull *)result.currencyCode == [NSNull null]) {
    result.currencyCode = nil;
  }
  result.countryCode = dict[@"countryCode"];
  if ((NSNull *)result.countryCode == [NSNull null]) {
    result.countryCode = nil;
  }
  result.isRecurring = dict[@"isRecurring"];
  if ((NSNull *)result.isRecurring == [NSNull null]) {
    result.isRecurring = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", (self.amountValue ? self.amountValue : [NSNull null]), @"amountValue", (self.currencyCode ? self.currencyCode : [NSNull null]), @"currencyCode", (self.countryCode ? self.countryCode : [NSNull null]), @"countryCode", (self.isRecurring ? self.isRecurring : [NSNull null]), @"isRecurring", nil];
}
@end

@implementation FLTGetPaymentProductRequest
+(FLTGetPaymentProductRequest*)fromMap:(NSDictionary*)dict {
  FLTGetPaymentProductRequest* result = [[FLTGetPaymentProductRequest alloc] init];
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  result.paymentProductId = dict[@"paymentProductId"];
  if ((NSNull *)result.paymentProductId == [NSNull null]) {
    result.paymentProductId = nil;
  }
  result.amountValue = dict[@"amountValue"];
  if ((NSNull *)result.amountValue == [NSNull null]) {
    result.amountValue = nil;
  }
  result.currencyCode = dict[@"currencyCode"];
  if ((NSNull *)result.currencyCode == [NSNull null]) {
    result.currencyCode = nil;
  }
  result.countryCode = dict[@"countryCode"];
  if ((NSNull *)result.countryCode == [NSNull null]) {
    result.countryCode = nil;
  }
  result.isRecurring = dict[@"isRecurring"];
  if ((NSNull *)result.isRecurring == [NSNull null]) {
    result.isRecurring = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", (self.paymentProductId ? self.paymentProductId : [NSNull null]), @"paymentProductId", (self.amountValue ? self.amountValue : [NSNull null]), @"amountValue", (self.currencyCode ? self.currencyCode : [NSNull null]), @"currencyCode", (self.countryCode ? self.countryCode : [NSNull null]), @"countryCode", (self.isRecurring ? self.isRecurring : [NSNull null]), @"isRecurring", nil];
}
@end

@implementation FLTPaymentContextResponse
+(FLTPaymentContextResponse*)fromMap:(NSDictionary*)dict {
  FLTPaymentContextResponse* result = [[FLTPaymentContextResponse alloc] init];
  result.basicPaymentProduct = dict[@"basicPaymentProduct"];
  if ((NSNull *)result.basicPaymentProduct == [NSNull null]) {
    result.basicPaymentProduct = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.basicPaymentProduct ? self.basicPaymentProduct : [NSNull null]), @"basicPaymentProduct", nil];
}
@end

@implementation FLTDisplayHintsPaymentItem
+(FLTDisplayHintsPaymentItem*)fromMap:(NSDictionary*)dict {
  FLTDisplayHintsPaymentItem* result = [[FLTDisplayHintsPaymentItem alloc] init];
  result.displayOrder = dict[@"displayOrder"];
  if ((NSNull *)result.displayOrder == [NSNull null]) {
    result.displayOrder = nil;
  }
  result.label = dict[@"label"];
  if ((NSNull *)result.label == [NSNull null]) {
    result.label = nil;
  }
  result.logoUrl = dict[@"logoUrl"];
  if ((NSNull *)result.logoUrl == [NSNull null]) {
    result.logoUrl = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.displayOrder ? self.displayOrder : [NSNull null]), @"displayOrder", (self.label ? self.label : [NSNull null]), @"label", (self.logoUrl ? self.logoUrl : [NSNull null]), @"logoUrl", nil];
}
@end

@implementation FLTPaymentProduct
+(FLTPaymentProduct*)fromMap:(NSDictionary*)dict {
  FLTPaymentProduct* result = [[FLTPaymentProduct alloc] init];
  result.id = dict[@"id"];
  if ((NSNull *)result.id == [NSNull null]) {
    result.id = nil;
  }
  result.paymentMethod = dict[@"paymentMethod"];
  if ((NSNull *)result.paymentMethod == [NSNull null]) {
    result.paymentMethod = nil;
  }
  result.paymentProductGroup = dict[@"paymentProductGroup"];
  if ((NSNull *)result.paymentProductGroup == [NSNull null]) {
    result.paymentProductGroup = nil;
  }
  result.minAmount = dict[@"minAmount"];
  if ((NSNull *)result.minAmount == [NSNull null]) {
    result.minAmount = nil;
  }
  result.maxAmount = dict[@"maxAmount"];
  if ((NSNull *)result.maxAmount == [NSNull null]) {
    result.maxAmount = nil;
  }
  result.allowsRecurring = dict[@"allowsRecurring"];
  if ((NSNull *)result.allowsRecurring == [NSNull null]) {
    result.allowsRecurring = nil;
  }
  result.allowsTokenization = dict[@"allowsTokenization"];
  if ((NSNull *)result.allowsTokenization == [NSNull null]) {
    result.allowsTokenization = nil;
  }
  result.usesRedirectionTo3rdParty = dict[@"usesRedirectionTo3rdParty"];
  if ((NSNull *)result.usesRedirectionTo3rdParty == [NSNull null]) {
    result.usesRedirectionTo3rdParty = nil;
  }
  result.displayHints = [FLTDisplayHintsPaymentItem fromMap:dict[@"displayHints"]];
  if ((NSNull *)result.displayHints == [NSNull null]) {
    result.displayHints = nil;
  }
  result.fields = dict[@"fields"];
  if ((NSNull *)result.fields == [NSNull null]) {
    result.fields = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.id ? self.id : [NSNull null]), @"id", (self.paymentMethod ? self.paymentMethod : [NSNull null]), @"paymentMethod", (self.paymentProductGroup ? self.paymentProductGroup : [NSNull null]), @"paymentProductGroup", (self.minAmount ? self.minAmount : [NSNull null]), @"minAmount", (self.maxAmount ? self.maxAmount : [NSNull null]), @"maxAmount", (self.allowsRecurring ? self.allowsRecurring : [NSNull null]), @"allowsRecurring", (self.allowsTokenization ? self.allowsTokenization : [NSNull null]), @"allowsTokenization", (self.usesRedirectionTo3rdParty ? self.usesRedirectionTo3rdParty : [NSNull null]), @"usesRedirectionTo3rdParty", (self.displayHints ? [self.displayHints toMap] : [NSNull null]), @"displayHints", (self.fields ? self.fields : [NSNull null]), @"fields", nil];
}
@end

@implementation FLTPaymentRequest
+(FLTPaymentRequest*)fromMap:(NSDictionary*)dict {
  FLTPaymentRequest* result = [[FLTPaymentRequest alloc] init];
  result.values = dict[@"values"];
  if ((NSNull *)result.values == [NSNull null]) {
    result.values = nil;
  }
  result.paymentProductId = dict[@"paymentProductId"];
  if ((NSNull *)result.paymentProductId == [NSNull null]) {
    result.paymentProductId = nil;
  }
  result.tokenize = dict[@"tokenize"];
  if ((NSNull *)result.tokenize == [NSNull null]) {
    result.tokenize = nil;
  }
  result.sessionId = dict[@"sessionId"];
  if ((NSNull *)result.sessionId == [NSNull null]) {
    result.sessionId = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.values ? self.values : [NSNull null]), @"values", (self.paymentProductId ? self.paymentProductId : [NSNull null]), @"paymentProductId", (self.tokenize ? self.tokenize : [NSNull null]), @"tokenize", (self.sessionId ? self.sessionId : [NSNull null]), @"sessionId", nil];
}
@end

@implementation FLTPreparedPaymentRequest
+(FLTPreparedPaymentRequest*)fromMap:(NSDictionary*)dict {
  FLTPreparedPaymentRequest* result = [[FLTPreparedPaymentRequest alloc] init];
  result.encryptedFields = dict[@"encryptedFields"];
  if ((NSNull *)result.encryptedFields == [NSNull null]) {
    result.encryptedFields = nil;
  }
  result.encodedClientMetaInfo = dict[@"encodedClientMetaInfo"];
  if ((NSNull *)result.encodedClientMetaInfo == [NSNull null]) {
    result.encodedClientMetaInfo = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.encryptedFields ? self.encryptedFields : [NSNull null]), @"encryptedFields", (self.encodedClientMetaInfo ? self.encodedClientMetaInfo : [NSNull null]), @"encodedClientMetaInfo", nil];
}
@end

@interface FLTApiCodecReader : FlutterStandardReader
@end
@implementation FLTApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 127:     
      return [FLTGetPaymentProductRequest fromMap:[self readValue]];
    
    case 126:     
      return [FLTPaymentContextRequest fromMap:[self readValue]];
    
    case 125:     
      return [FLTPaymentContextResponse fromMap:[self readValue]];
    
    case 124:     
      return [FLTPaymentProduct fromMap:[self readValue]];
    
    case 123:     
      return [FLTPaymentRequest fromMap:[self readValue]];
    
    case 122:     
      return [FLTPreparedPaymentRequest fromMap:[self readValue]];
    
    case 121:     
      return [FLTSessionRequest fromMap:[self readValue]];
    
    case 120:     
      return [FLTSessionResponse fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTGetPaymentProductRequest class]]) {
    [self writeByte:127];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTPaymentContextRequest class]]) {
    [self writeByte:126];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTPaymentContextResponse class]]) {
    [self writeByte:125];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTPaymentProduct class]]) {
    [self writeByte:124];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTPaymentRequest class]]) {
    [self writeByte:123];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTPreparedPaymentRequest class]]) {
    [self writeByte:122];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTSessionRequest class]]) {
    [self writeByte:121];
    [self writeValue:[value toMap]];
  }
  else if ([value isKindOfClass:[FLTSessionResponse class]]) {
    [self writeByte:120];
    [self writeValue:[value toMap]];
  }
  else {
    [super writeValue:value];
  }
}
@end

@interface FLTApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTApiCodecReaderWriter
- (FlutterStandardWriter*)writerWithData:(NSMutableData*)data {
  return [[FLTApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader*)readerWithData:(NSData*)data {
  return [[FLTApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec>* FLTApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec* s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    FLTApiCodecReaderWriter* readerWriter = [[FLTApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.initClientSession"
        binaryMessenger:binaryMessenger
        codec:FLTApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FLTSessionRequest *input = [FLTSessionRequest fromMap:message];
        FlutterError *error;
        FLTSessionResponse *output = [api initClientSession:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.getBasicPaymentItems"
        binaryMessenger:binaryMessenger
        codec:FLTApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FLTPaymentContextRequest *input = [FLTPaymentContextRequest fromMap:message];
        [api getBasicPaymentItems:input completion:^(FLTPaymentContextResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult([output toMap], error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.getPaymentProduct"
        binaryMessenger:binaryMessenger
        codec:FLTApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FLTGetPaymentProductRequest *input = [FLTGetPaymentProductRequest fromMap:message];
        [api getPaymentProduct:input completion:^(FLTPaymentProduct *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult([output toMap], error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.preparePaymentRequest"
        binaryMessenger:binaryMessenger
        codec:FLTApiGetCodec()];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FLTPaymentRequest *input = [FLTPaymentRequest fromMap:message];
        [api preparePaymentRequest:input completion:^(FLTPreparedPaymentRequest *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult([output toMap], error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
